#!/usr/bin/python2.7

import socket
import argparse


def main():
    
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument('--server_ip', type=str, default='localhost', help='ip address of the server')
    arg_parser.add_argument('--server_port', type=int, default=1234, help='port of the server')
    arg_parser.add_argument('-v', '--verbose', action='store_true', help='verbose output of qstat')
    args = arg_parser.parse_args()

    server_address = (args.server_ip, args.server_port)
    verbose = 'verbose' if args.verbose else 'quiet'

    try:
        sock = socket.socket( socket.AF_INET, socket.SOCK_STREAM )
        sock.settimeout(10.0)
        sock.connect(server_address)
        sock.sendall('qstat:' + verbose)
        # print header
        if not args.verbose:
            print '+----------------------------------------------------------------------------+'
            print '|id               jobname    submit/start time  status         user  priority|'
            print '+----------------------------------------------------------------------------+'
        else:
            print '+-----------------------------------------------------------------------------------------------------------------+'
            print '|id               jobname    submit/start time  status         user  priority  threads    memory  time limit  gpus|'
            print '+-----------------------------------------------------------------------------------------------------------------+'
        # print jobs
        reply = ''
        while not reply == 'done':
            reply = sock.recv(1024)
            if not reply == 'done':
                print reply
            if reply == '': # empty reply -> server closed socket -> done
                reply = 'done'
        sock.close()
        # print footer
        if not args.verbose:
            print '+----------------------------------------------------------------------------+'
        else:
            print '+-----------------------------------------------------------------------------------------------------------------+'
    except:
        print 'qstat: no answer from server'


if __name__ == '__main__':
    main()
